config/routes.rb
Rails.application.routes.draw do
  root 'stages#thisweek'
  
  get 'stages/playing',  to: 'stages#playing'
  get 'stages/thisweek', to: 'stages#thisweek'
  get 'stages/later',    to: 'stages#later'
  get 'stages/detail/:id', to: 'stages#detail'
  resources :stages, only: [:show]
  
  get 'stages/json/playing',  to: 'stages_json#playing'
  get 'stages/json/thisweek', to: 'stages_json#thisweek'
  get 'stages/json/later',    to: 'stages_json#later'
  
  post 'alerts/create', to: 'alerts#create'
  get 'help', to: 'static_pages#help'
  get 'calendar', to: 'calendar#index'
  get 'stars/set/:id', to: 'stars#set'
  get 'stars/unset/:id', to: 'stars#unset'
  get 'signup', to: 'users#new'
  post 'signup',  to: 'users#create'
  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  resources :users

  get 'stage_search/', to: 'stage_search#index'
  post 'stage_search/', to: 'stage_search#search'
  
  get  'contact',         to: 'contacts#index'
  post 'contact/confirm', to: 'contacts#confirm'
  post 'contact/sent',    to: 'contacts#sent'
  
  post 'area/set',        to: 'area#create'
  
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<div class="help-page">

<h1>PLAY ALERTとは</h1>
<p>
PLAY ALERT は、小劇場の観劇が好きな方向けに作られたWebサービスです。<br>
<ul>
  <li>観たい公演が大量に重なっていてスケジュール管理できない！</li>
  <li>昼の仕事は忙しいけど好きな劇団の舞台は欠かさず観たい！</li>
</ul>
そんな方に向けて作られています。
</p>


<h1>☆マークとカレンダー表示について</h1>
<p>
公演の一覧エリアから観たい（または気になる）公演の☆マークをクリックすると、☆が黄色になります。  <br>
☆マークをつけた公演一覧は、画面右上のカレンダーでスケジュールを確認することができます。<br>
<span class="sub-msg">（今のところこの機能がPLAY ALERTの主要機能です）</span>
</p>

<h1>ユーザー登録について</h1>
<p>
  ☆マークの情報ですが、通常はブラウザを閉じたり時間が経ったりすると消えてしまいます。<br>
  どの公演に☆マークをつけたかをシステムに覚えさせたい場合は、新規にユーザー登録をしたうえで、ログインしてください。<br>
  <ul>
    <li><%= link_to "新規ユーザー登録", signup_path %></li>
    <li><%= link_to "ログイン", login_path %></li>
  </ul>
  ログインすると、公演ごとに「アラートメール」機能を使えるようになります。<br>
  <span class="sub-msg">（ちなみにログイン情報をパソコンに覚えさせたり、パスワードを忘れてしまった方向けの機能も近日中に作る予定です。）</span>
</p>

<h1>【ログインユーザー向け】アラートメール機能について</h1>
<p>
  ログインユーザーの方は、各公演ごとに「初日の7日前」「初日の3日前」「初日の1日前」にメールを送る機能があります。<br>
  設定後、数分以内に「通知確認」メールが届いたら設定完了です。<br>
  もしメールが届かない場合は、<span style="font-weight:bold;">@gmail.com</span> からのメールが届くように設定をお願いします。<br>
  <span class="sub-msg">（こちらの機能ですが、アラート通知を送る日にちが飛び飛びでしか選べなかったり、初日が過ぎてしまった公演に対してはメールが送れなかったりするので、別途大きく改修を加えると思います。）</span>
</p>

<h1>今後の予定について</h1>
<p>
  主にログインユーザー向けに、以下のような機能を構想中（妄想中？）です。
<ul>
  <li>ユーザー名とパスワードをブラウザに保存する機能</li>
  <li>パスワードリマインダー機能</li>
  <li>「来週以降～」の公演数がたくさんあるので、どの週の公演かを選択肢で選べるようにする</li>
  <li>アラートメールは初日の7日前～公演の最終日まで選べるようにする</li>
  <li>観る日を決めたら「この日に観る」マークを日ごとにつけられるようにする。カレンダーにはその公演の観る日１日だけに線が出るようにする。</li>
  <li>気に入った劇団や俳優名を登録したら、公演が登録されたタイミングで通知する機能</li>
  <li>Twitter IDでログインできるようにする</li>
</ul>
</p>

<h1>お問い合わせ</h1>
<%= link_to "お問い合わせフォーム", contact_path %> よりお願いします。
</div>