config/routes.rb
Rails.application.routes.draw do
  root 'stages#thisweek'
  
  get 'stages/playing',  to: 'stages#playing'
  get 'stages/thisweek', to: 'stages#thisweek'
  get 'stages/later',    to: 'stages#later'
  get 'stages/detail/:id', to: 'stages#detail'
  resources :stages, only: [:show]
  
  get 'stages/json/playing',  to: 'stages_json#playing'
  get 'stages/json/thisweek', to: 'stages_json#thisweek'
  get 'stages/json/later',    to: 'stages_json#later'
  
  post 'alerts/create', to: 'alerts#create'
  get 'help', to: 'static_pages#help'
  get 'calendar', to: 'calendar#index'
  get 'stars/set/:id', to: 'stars#set'
  get 'stars/unset/:id', to: 'stars#unset'
  get 'signup', to: 'users#new'
  post 'signup',  to: 'users#create'
  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  resources :users

  get 'stage_search/', to: 'stage_search#index'
  post 'stage_search/', to: 'stage_search#search'
  
  get  'contact',         to: 'contacts#index'
  post 'contact/confirm', to: 'contacts#confirm'
  post 'contact/sent',    to: 'contacts#sent'
  
  post 'area/set',        to: 'area#create'
  
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  attr_accessor :name, :email, :body
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
  end
  
  def confirm
    @contact = Contact.new(contact_params)
  end
  
  def sent
    @contact = Contact.new(contact_params)
    StageMailer.contact(@contact).deliver_now
  end
  
  private
  def contact_params
    params.require(:contact).permit(
        :name, :body
      )
  end
end

app/views/contacts/confirm.html.erb
<div class="help-page">
  <h1>お問い合わせの確認</h1>
  <div class="row">
    <div class="col-sm-12">お名前 : </div>
    <div class="col-sm-12" style="color: #44f;"><%= @contact.name %></div>
    <div class="col-sm-12"><br></div>
    
    <div class="col-sm-12">お問い合わせ内容 : </div>
    <div class="col-sm-12" style="color: #44f;"><%= @contact.body %></div>

  </div>
  
  <%= form_for(@contact, url: contact_sent_path) do |f| %>
    <%= f.hidden_field :name, value: @contact.name %>
    <%= f.hidden_field :body, value: @contact.body %>
  以上の内容でよろしいでしょうか？<br>
  <%= f.submit '送信', class: "btn btn-info" %>
  <% end %>

</div>

app/views/contacts/index.html.erb
<div class="help-page">
  <h1>お問い合わせ</h1>
  <p>
    <ul>
      <li>使い方に関してのご質問</li>
      <li>新しい機能のご要望</li>
      <li>ご意見・ご感想</li>
    </ul>
    等々ございましたら、こちらのフォームからお気軽にお問い合わせください！
  </p>
  <br>
  <%= form_for(@contact, url: contact_confirm_path) do |f|%>
  <div class="row">
    <div class="col-sm-12"><%= f.label :name, 'お名前（任意）:' %></div>
    <div class="col-sm-12"><%= f.text_field :name %></div>

    <div class="col-sm-12"><%= f.label :body, 'お問い合わせの内容:' %></div>
    <div class="col-sm-12"><%= f.text_area :body, rows: 6 %></div>
    
    <div class="col-sm-12">&nbsp;</div>
    <%= f.submit '確認', class: "btn btn-info" %>
  </div>
<% end %>

</div>

app/views/contacts/sent.html.erb
<div class="help-page">
  <h1>送信完了</h1>
  <p>お問い合わせいただき、ありがとうございました！</p>
</div>