config/routes.rb
Rails.application.routes.draw do
  root 'stages#thisweek'
  
  get 'stages/playing',  to: 'stages#playing'
  get 'stages/thisweek', to: 'stages#thisweek'
  get 'stages/later',    to: 'stages#later'
  get 'stages/detail/:id', to: 'stages#detail'
  resources :stages, only: [:show]
  
  get 'stages/json/playing',  to: 'stages_json#playing'
  get 'stages/json/thisweek', to: 'stages_json#thisweek'
  get 'stages/json/later',    to: 'stages_json#later'
  
  post 'alerts/create', to: 'alerts#create'
  get 'help', to: 'static_pages#help'
  get 'calendar', to: 'calendar#index'
  get 'stars/set/:id', to: 'stars#set'
  get 'stars/unset/:id', to: 'stars#unset'
  get 'signup', to: 'users#new'
  post 'signup',  to: 'users#create'
  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  resources :users

  get 'stage_search/', to: 'stage_search#index'
  post 'stage_search/', to: 'stage_search#search'
  
  get  'contact',         to: 'contacts#index'
  post 'contact/confirm', to: 'contacts#confirm'
  post 'contact/sent',    to: 'contacts#sent'
  
  post 'area/set',        to: 'area#create'
  
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/stage.rb
class Stage < ApplicationRecord
  validates :url,     presence: true, length: { maximum: 255 }
  validates :title,   presence: true, length: { maximum: 255 }
  validates :group,   presence: true, length: { maximum: 255 }
  validates :theater, presence: true, length: { maximum: 255 }
  validates :startdate, presence: true
  validates :enddate,   presence: true
  has_many :alerts, dependent: :destroy
  has_many :user_stars, dependent: :destroy
  has_one :stage_detail, dependent: :destroy

  include StagesHelper

  def term
    return datejapan_short(startdate) if startdate == enddate
    datejapan_short(startdate) + "〜 " + datejapan_short(enddate) 
  end

  class << self
    include StagesHelper
    def search(word)
      relation = Stage.joins(:stage_detail)
      relation
        .merge(Stage.where("title ILIKE ?", "%#{sanitize_sql_like(word)}%"))
        .or(relation.where("\"group\" ILIKE ?", "%#{sanitize_sql_like(word)}%"))
        .or(relation.where("theater ILIKE ?", "%#{sanitize_sql_like(word)}%"))
        .or(relation.where("stage_details.playwright ILIKE ?",  "%#{sanitize_sql_like(word)}%"))
        .or(relation.where("stage_details.director ILIKE ?",  "%#{sanitize_sql_like(word)}%"))
        .or(relation.where("stage_details.cast ILIKE ?",  "%#{sanitize_sql_like(word)}%"))
        .order(:startdate)
    end
  
    def count_on_week(area, firstday_of_week)
      Stage
        .where("startdate >= ?", firstday_of_week)
        .where("startdate <= ?", firstday_of_week + 6)
        .where(area: area)
        .size
    end
  
    def playing(area, page=1)
      Stage
        .where("startdate <= ?", Date.today)
        .where(area: area)
        .order(:startdate, :id)
        .page(page)
    end
    
    def thisweek(area, page=1)
      first = firstofweek(Date.today)
      last  = lastofweek(Date.today)
      Stage
        .where("startdate >= ?", first)
        .where("startdate <= ?", last)
        .where(area: area)
        .order(:startdate, :id)
        .page(page)
    end
    
    def later(area, page, start)
      start = DateTime.strptime(start, "%Y%m%d")
      Stage
        .where("startdate >= ?", start)
        .where("startdate <= ?", start + 6)
        .where(area: area)
        .order(:startdate, :id)
        .page(page)
    end

  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  include StagesHelper
  before_action :set_area, only: [:playing, :thisweek, :later]
  before_action :set_stages_on_weeks, only: [:playing, :thisweek, :later]
  before_action :set_prevweek_link, only: [:thisweek, :later]
  before_action :set_nextweek_link, only: [:thisweek, :later]
  
  def show
    @stage = Stage.find(params[:id])
    @alert = Alert.new
  end
  
  def detail
    @stage_detail = StageDetail.find_by(stage_id: params[:id])
    if @stage_detail
      render json: @stage_detail.json
    else
      render json: {status: "notfound"}
    end
  end
  
  def playing
    @stages = Stage.playing @area
    @view = 'playing'
    render :index
  end
  
  def thisweek
    @stages = Stage.thisweek @area
    @view = 'thisweek'
    render :index
  end
  
  def later
    if params[:start].nil?
      last  = lastofweek(Date.today)
      @stages = Stage
        .where("startdate > ?", last)
        .where(area: @area)
        .order(:startdate, :id)
        .page(params[:page])
    else
      @stages = Stage.later(@area, 1, params[:start])
    end
    @view = 'later'
    render :index
  end

  def set_area
    @area = session[:area] || Constants::AREA_KANTO
  end

  private

  def set_stages_on_weeks
    date = Date.today
    @stages_on_weeks = []
    loop do
      firstday = nextweek_first date
      count = Stage.count_on_week(@area, firstday)
      break if count == 0
      @stages_on_weeks.push({
        firstday: firstday,
        text: firstday.strftime('%Y-%m-%d') + "〜" + (firstday + 6).strftime('%Y-%m-%d') + " (#{count}件)",
        url: "/stages/later?start=" + firstday.strftime('%Y%m%d'),
        size: count
      })
      date = firstday
    end
  end

  def set_prevweek_link
    return if @stages_on_weeks.nil? or @stages_on_weeks.empty?
    return if params[:start].nil?
    idx = 0
    @stages_on_weeks.each_with_index do |sw, i|
      if sw[:url].match(params[:start])
        idx = i - 1
        break
      end
    end
    url = idx < 0 ? '/stages/thisweek' : @stages_on_weeks[idx][:url]
    @prevweek_link = url.nil? ? nil : { text: '←前の週', url: url }
  end

  def set_nextweek_link
    return if @stages_on_weeks.nil? or @stages_on_weeks.empty?
    if params[:start].nil?
      url = @stages_on_weeks.first[:url]
    else
      idx = 0
      @stages_on_weeks.each_with_index do |sw, i|
        if sw[:url].match(params[:start])
          idx = i + 1
          break
        end
      end
      if @stages_on_weeks.count == idx
        url = nil
      else
        url = @stages_on_weeks[idx][:url]
      end
    end
    @nextweek_link = url.nil? ? nil : { text: '次の週→', url: url }
  end
end

app/helpers/stages_helper.rb
module StagesHelper
  CWDAY_SATURDAY = 6
  CWDAY_SUNDAY   = 7
  
  def dayoftheweek(date)
    %w(日 月 火 水 木 金 土 日)[date.cwday]
  end
  
  # 2017-10-18 ->  2017年10月18日(水) 
  def datejapan(date)
    if m = date.to_s.match(/(?<year>\d+)-(?<month>\d+)-(?<day>\d+)/)
      m[:year] + "年" + cut_firstzero(m[:month]) + "月" + cut_firstzero(m[:day]) + "日" + "(" + dayoftheweek(date) + ")"
    else 
      ''
    end
  end
  
  def datejapan_short(date)
    if m = date.to_s.match(/(?<year>\d+)-(?<month>\d+)-(?<day>\d+)/)
      cut_firstzero(m[:month]) + "月" + cut_firstzero(m[:day]) + "日" + "(" + dayoftheweek(date) + ")"
    else
      ''
    end
  end
  
  def cut_firstzero(str)
    str.gsub(/0([1-9])/, '\1')
  end
  
  def glyphicon_star(stage_id)
    stars.include?(stage_id.to_s) ? "glyphicon-star" : "glyphicon-star-empty"
  end
  
  def is_visible?(str)
    return false if str.nil?
    return false if str.strip.empty?
    true
  end
  
  def stagenavi_onoff(viewname)
    return ' on' if @view == viewname
    ''
  end
  
  def stagelist_title_class
    if @view == 'playing'
      'nowplaying'
    elsif @view == 'later'
      'later'
    else
      ''
    end
  end
  
  def firstofweek(date)
    return date if date.cwday == CWDAY_SUNDAY
    firstofweek date - 1
  end

  def lastofweek(date)
    return date if date.cwday == CWDAY_SATURDAY
    lastofweek date + 1
  end
  
  def nextweek_first(date)
    date += 7
    firstofweek date
  end
  
  def nextweek_last(date)
    date += 7
    lastofweek date
  end

  def lastweek_first(date)
    date -= 7
    firstofweek date
  end

  def prevweek_first
    firstday = lastweek_first Date.strptime(params[:start], '%Y%m%d')
    return nil if Stage.count_on_week(firstday) == 0
    firstday
  end

end

app/views/stages/_counter.html.erb
<div class="counter">
  <%= @stages.total_count %>件
</div>

app/views/stages/_stage.html.erb
    <%= content_tag(:div, class: "stage-choice", 'data-choice' => stage_path(stage.id), 'stage-id' => stage.id) do %>
      <%= content_tag(:span, stage.title, class: "stage-title") %>&nbsp;&nbsp;
      <%= content_tag(:span, stage.group, class: "stage-group") %><br>
      <%= content_tag(:span, class: "stage-detail") do %>
        <%= content_tag(:span, stage.term, class: "stage-term") %><br>
        <%= content_tag(:span, stage.theater, class: "stage-theater") %>&nbsp;&nbsp;
      <% end %>
      <%= link_to "", "", class: "glyphicon icon-link star " + glyphicon_star(stage.id) %>
    <% end %>

app/views/stages/_stagelist_area.html.erb
<div id="stagelist_area">
<% keydate = '' %>
<% @stages.each do |stage| %>
<%   if keydate != stage.startdate %>
    <div class="stagelist-title <%= stagelist_title_class %>" data-startdate="<%= stage.startdate %>">
      <%= datejapan(stage.startdate) %><span class="stagelist-tilde">〜</span>
    </div>
    <% keydate = stage.startdate %>
<%   end %>
    <%= render 'shared/stage', stage: stage %>
<% end %>
</div>

<a href="" class="pagetop"><span class="glyphicon glyphicon-chevron-up"></span></a>
<div id="loading"></div>
<form><input type="text" id="pages" value="" style="display: none"></form>

<%= render 'shared/popup' %>

app/views/stages/index.html.erb
<%= render 'shared/header_signup' %>

<%= render 'counter' %>

<%= @debug %>

<!--
<div class="tips tips-head">
  観たい・気になる公演の☆マークをつけると、その公演のスケジュールがカレンダー（右上のアイコン）に登録されます！ 
  &nbsp;<%= link_to "ヘルプ", help_path %>
</div>
-->
<div class="select_area">
    <span class="select_area--east<%= (@area == Constants::AREA_KANTO ? ' select_area--active': '') %>">関東</span>
    <span class="select_area--west<%= (@area == Constants::AREA_KINKI ? ' select_area--active': '') %>">関西</span>
</div>
<%= link_to "上演中", stages_playing_path, 
    class: 'stagenavi-playing' + stagenavi_onoff('playing') %> 
<%= link_to "今週〜", stages_thisweek_path,
    class: 'stagenavi-thisweek' + stagenavi_onoff('thisweek') %>
<%= link_to '#',
    class: 'stagenavi-later' + stagenavi_onoff('later') do %>
    来週以降〜&nbsp;<span class="glyphicon glyphicon-chevron-down" style="font-size: 0.8em"></span>
<% end %>

<ul class="later-list" id="later-list-1">
<% latermax = 5 %>
<% @stages_on_weeks.each_with_index do |stage_on_week, i| %>
    <% if i <= latermax %>
        <li><%= link_to stage_on_week[:text], stage_on_week[:url] %></li>
    <% end %>
<% end %>
<% if @stages_on_weeks.count > latermax %>
    <li><a href="" id="later-list-more">もっとみる..</a></li>
<% end %>
</ul>

<ul class="later-list" id="later-list-2">
<% @stages_on_weeks.each do |stage_on_week| %>
    <li><%= link_to stage_on_week[:text], stage_on_week[:url] %></li>
<% end %>
</ul>
<br />
<%= render 'stagelist_area' %>

<div class="footer-navi">
  <%= link_to @prevweek_link[:text], @prevweek_link[:url], class: "prevweek-link" unless @prevweek_link.nil? %>
  <%= link_to @nextweek_link[:text], @nextweek_link[:url], class: "nextweek-link" unless @nextweek_link.nil? %>
</div>

app/views/stages/show.html.erb
<div id="popup-title"><%= @stage.title %></div>
<span id="popup-group"><%= @stage.group %></span><br>
<div id="popup-term"><%= datejapan(@stage.startdate) %>～ <%= datejapan(@stage.enddate) %></div>
<div id="popup-theater"><%= @stage.theater %></div>

<!--
<div style="font-size:1.0em; color: #999;">
  詳しい情報は<%= link_to 'こちら', 'http://stage.corich.jp' + @stage.url,
                  target: '_blank',
                  rel: 'noreferrer' %>
</div>
-->

<% unless @stage.stage_detail.nil? %>

<% if is_visible?(@stage.stage_detail.playwright) %>
<div class="detail-title">脚本</div>
<div class="detail-content"><%= @stage.stage_detail.playwright %></div>
<% end %>

<% if is_visible?(@stage.stage_detail.director) %>
<div class="detail-title">演出</div>
<div class="detail-content"><%= @stage.stage_detail.director %></div>
<% end %>

<% if is_visible?(@stage.stage_detail.cast) %>
<div class="detail-title">出演</div>
<div class="detail-content"><%= @stage.stage_detail.cast %></div>
<% end %>

<% if is_visible?(@stage.stage_detail.price) %>
<div class="detail-title">チケット</div> 
<div class="detail-content"><%= @stage.stage_detail.price.html_safe %></div>
<% end %>

<% if is_visible?(@stage.stage_detail.timetable) %>
<div class="detail-title">タイムテーブル</div>
<div class="detail-content"><%= @stage.stage_detail.timetable.html_safe %></div>
<% end %>

<% if is_visible?(@stage.stage_detail.site) %>
<div class="detail-title">公式サイト</div>
<div class="detail-content">
  <%= link_to @stage.stage_detail.site, @stage.stage_detail.site, target: '_blank' %>
  <br>
  <span style="color: blue;">最新の情報は公式サイトにてご確認ください。</span>  
</div>
<% end %>

<% end %>

<% if logged_in? %>
  <% if @stage.startdate <= Date.today %>
    <br>
    <span style="color: #888;">この公演は初日を迎えたものなので、初日より前にアラートメールを送る機能は無効になります。</span>
  <% else %>
<section>
  <div class="alert-on-notlogin">
    <%= form_for(@alert, url: {controller: 'alerts', action: 'create'}) do |f| %>
    
    <%= f.hidden_field :stage_id, value: @stage.id %>
    <span class="popup-alert">公演が始まる前に通知でお知らせを受けたい場合は、以下をチェックして「メールで通知する」ボタンを押してください！</span>
    <br><br>
    <p>
      <%= f.check_box :seven_days, {}, "true", "false" %>
      <span class="alert-text">初日の7日前</span><br>
      <%= f.check_box :three_days, {}, 'true', 'false' %>
      <span class="alert-text">初日の3日前</span><br>
      <%= f.check_box :one_day, {checked: true}, 'true', 'false' %>
      <span class="alert-text">初日の1日前</span><br>
    </p>
    <%= f.submit "メールで通知する", class: "btn btn-primary" %>
    <% end %>
  </div>
</section>
  <% end %>
  
<% else %>
  <br>
  <div class="tips">
    公演が始まる前に通知でお知らせを受けたい場合は、ログインしてください！
  </div>
<% end %>