config/routes.rb
Rails.application.routes.draw do
  root 'stages#thisweek'
  
  get 'stages/playing',  to: 'stages#playing'
  get 'stages/thisweek', to: 'stages#thisweek'
  get 'stages/later',    to: 'stages#later'
  get 'stages/detail/:id', to: 'stages#detail'
  resources :stages, only: [:show]
  
  get 'stages/json/playing',  to: 'stages_json#playing'
  get 'stages/json/thisweek', to: 'stages_json#thisweek'
  get 'stages/json/later',    to: 'stages_json#later'
  
  post 'alerts/create', to: 'alerts#create'
  get 'help', to: 'static_pages#help'
  get 'calendar', to: 'calendar#index'
  get 'stars/set/:id', to: 'stars#set'
  get 'stars/unset/:id', to: 'stars#unset'
  get 'signup', to: 'users#new'
  post 'signup',  to: 'users#create'
  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  resources :users

  get 'stage_search/', to: 'stage_search#index'
  post 'stage_search/', to: 'stage_search#search'
  
  get  'contact',         to: 'contacts#index'
  post 'contact/confirm', to: 'contacts#confirm'
  post 'contact/sent',    to: 'contacts#sent'
  
  post 'area/set',        to: 'area#create'
  
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PLAY ALERT</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  </head>

  <body>
    <header class="navbar navbar-fixed-top">
      <div class="container">
        <%= link_to "PLAY ALERT", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <%= link_to "", root_path, class: "glyphicon glyphicon-home nav-link" %>
            <%= link_to "", calendar_path, class: "glyphicon  glyphicon-calendar nav-link" %>
            <!-- <%= link_to "", help_path, class: "glyphicon glyphicon-question-sign nav-link" %> -->
            <!-- <div class="glyphicon glyphicon-user nav-link" id="usermenu_dropdown" style="display: inline;"></div> -->
            <%= link_to "", stage_search_path, class: "glyphicon glyphicon-search nav-link" %>
          </ul>
        </nav>
      </div>
      
      <div id="user_menu">
        <ul class="user_dropdown">
          <% if logged_in? %>
            <li><%= current_user.name %>さん、こんにちは！</li>
            <li class="user_dropdown_list"><%= link_to "ログアウト", logout_path, method: :delete %></li>
          <% else %>
            <li class="user_dropdown_list"><%= link_to "ログイン", login_path %></li>
            <li class="user_dropdown_list"><%= link_to "新規ユーザー登録", signup_path %></li>
          <% end %>
          <li class="user_dropdown_list"><%= link_to "ヘルプ", help_path %></li>
        </ul>
      </div>
    </header>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>